name: ugrip
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - aiohttp==3.8.4
    - aioredis==1.3.1
    - aiosignal==1.3.1
    - alembic==1.11.1
    - altair==5.0.1
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - blinker==1.6.2
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - comm==0.1.3
    - contourpy==1.0.7
    - courlan==0.9.3
    - cycler==0.11.0
    - databricks-cli==0.17.7
    - datasets==2.12.0
    - dateparser==1.1.8
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - docker==6.1.3
    - docopt==0.6.2
    - entrypoints==0.4
    - evaluate==0.4.0
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fairlib==0.1.0
    - fastapi==0.96.0
    - fastapi-cache==0.1.0
    - fastapi-cache2==0.2.1
    - fastjsonschema==2.17.1
    - fasttext==0.9.2
    - filelock==3.12.0
    - flask==2.3.2
    - flatbuffers==23.5.26
    - fonttools==4.39.4
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - gensim==4.3.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - greenlet==2.0.2
    - gunicorn==20.1.0
    - h11==0.14.0
    - hiredis==2.2.3
    - htmldate==1.4.3
    - huggingface-hub==0.14.1
    - idna==3.4
    - imageio==2.30.0
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - ipykernel==6.23.1
    - ipython==8.12.2
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - justext==3.0.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lazy-loader==0.2
    - libclang==16.0.0
    - lxml==4.9.2
    - mako==1.2.4
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.5
    - mlflow==2.3.2
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.4.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - nltk==3.8.1
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.23.5
    - oauthlib==3.2.2
    - openai==0.27.7
    - opencv-python==4.7.0.72
    - overrides==7.3.1
    - packaging==23.1
    - pandas==2.0.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pendulum==2.1.2
    - pexpect==4.8.0
    - pickle5==0.0.11
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.5.1
    - plotly==5.14.1
    - prettytable==2.5.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - protobuf==4.23.2
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.10.4
    - pycparser==2.21
    - pydantic==1.10.8
    - pydeck==0.8.1b0
    - pygments==2.15.1
    - pyjwt==2.7.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pytzdata==2020.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.1.0
    - querystring-parser==1.2.4
    - redis==4.5.5
    - regex==2023.5.5
    - requests==2.31.0
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.4.1
    - rsa==4.9
    - sacremoses==0.0.53
    - safetensors==0.3.1
    - scikit-image==0.20.0
    - scikit-learn==1.1.3
    - scipy==1.9.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - six==1.16.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.15
    - sqlalchemy-utils==0.41.1
    - sqlparse==0.4.4
    - stack-data==0.6.2
    - starlette==0.27.0
    - streamlit==1.23.1
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.2
    - tinycss2==1.2.1
    - tld==0.13
    - tokenizers==0.13.3
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.10.0+cu111
    - torchaudio==0.10.0+rocm4.1
    - torchvision==0.11.0+cu111
    - tornado==6.3.2
    - tqdm==4.65.0
    - trafilatura==1.6.0
    - traitlets==5.9.0
    - transformers==4.29.2
    - typing-extensions==4.6.2
    - tzdata==2023.3
    - tzlocal==4.3
    - uri-template==1.2.0
    - urllib3==1.26.16
    - uvicorn==0.22.0
    - validators==0.20.0
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.2
    - werkzeug==2.3.4
    - wrapt==1.14.1
    - xxhash==3.2.0
    - yarl==1.9.2
    - zipp==3.15.0
